swagger: "2.0"
info:
  title: Finance application API
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /api/v1/accounts:
    post:
      summary: Create new user account
      produces:
        - application/json
      consumes:
        - application/json
      tags: ["Accounts"]
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Account'
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - result
            properties:
              result:
                $ref: '#/definitions/Account'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Authorization error
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
  /api/v1/categories:
    post:
      summary: Create new user category
      produces:
        - application/json
      consumes:
        - application/json
      tags: ["Categories"]
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Category"
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - result
            properties:
              result:
                $ref: '#/definitions/Category'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Authorization error
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'
  /api/v1/tags:
    post:
      summary: Create new user tag
      produces:
        - application/json
      consumes:
        - application/json
      tags: ["Tags"]
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/Tag"
      responses:
        200:
          description: OK
          schema:
            type: object
            required:
              - result
            properties:
              result:
                $ref: '#/definitions/Tag'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Authorization error
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Account:
    type: object
    required:
      - title
    properties:
      id:
        type: integer
        example: 935
      title:
        type: string
        example: some account
      user_id:
        type: integer
        example: 246
      use_in_reports:
        type: boolean
        example: false
      start_balance:
        type: number
        example: 867.77
  Category:
    type: object
    required:
      - title
    properties:
      id:
        type: integer
        example: 935
      title:
        type: string
        example: some category
      icon:
        $ref: "#/definitions/Icon"
      color:
        $ref: "#/definitions/Color"
  Icon:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        example: 935
      name:
        type: string
        example: icon
      path:
        type: string
        example: path/to/icon
  Color:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        example: 935
      name:
        type: string
        example: color name
      color:
        type: string
        example: color name
  Tag:
    type: object
    required:
      - title
    properties:
      id:
        type: integer
        example: 935
      user_id:
        type: integer
        example: 1123
      title:
        type: string
        example: tag name
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        example: 400
      message:
        type: string
        example: bad request
