swagger: "2.0"
info:
  title: Finance application API
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /api/v1/accounts:
    post:
      summary: Create new user account
      produces:
        - application/json
      consumes:
        - application/json
      tags: ["Accounts"]
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
                example: some account
              use_in_reports:
                type: boolean
                example: false
              start_balance:
                type: number
                example: 867.77
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Account'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Authorization error
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: '#/definitions/Error'



definitions:
  Account:
    type: object
    required:
      - title
    properties:
      id:
        type: integer
        example: 935
      title:
        type: string
        example: some account
      user_id:
        type: integer
        example: 246
      use_in_reports:
        type: boolean
        example: false
      start_balance:
        type: number
        example: 867.77
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        example: 400
      message:
        type: string
        example: bad request
